# yaml-language-server: $schema=https://json.schemastore.org/traefik-v2-file-provider.json
# {{ if env "PROXY_UPSTREAMS" }}
tcp:
  routers:
  # {{ range $index, $value := regexSplit "[,\n]+" ( env "PROXY_UPSTREAMS" ) -1 | compact }}
    # {{ $upstream := regexSplit ":" $value -1 }}
    # {{ $host := index $upstream 0 }}
    # {{ $port := index $upstream 1 }}
    # {{ if gt ( len $upstream ) 2 }}
      # {{ $type := index $upstream 2 }}
    proxy-{{ $host }}-{{ $port }}-{{ $type }}:
      # {{ if eq $type "catchall" }}
      rule: 'HostSNI(`*`)'
      entryPoints: ["port{{ $port }}"]
      service: "proxy-{{ $host }}-{{ $port }}"
      # {{ else }}
        # {{ fail ( cat "Invalid type:" $type ) }}
      # {{ end }}
    # {{ else }}
    proxy-{{ $host }}-{{ $port }}:
      rule: 'HostSNI(`{{ $host }}`)'
      entryPoints: ["port{{ $port }}"]
      service: "proxy-{{ $host }}-{{ $port }}"
      tls: { passthrough: true }
    # {{ end }}
  # {{ end }}
  services:
  # {{ range $index, $value := regexSplit "[,\n]+" ( env "PROXY_UPSTREAMS" ) -1 | compact }}
    # {{ $upstream := regexSplit ":" $value -1 }}
    # {{ $host := index $upstream 0 }}
    # {{ $port := index $upstream 1 }}
    proxy-{{ $host }}-{{ $port }}:
      loadBalancer:
        servers: [{ address: "{{ $host }}:{{ $port }}" }]
  # {{ end }}
# {{ end }}
