# yaml-language-server: $schema=https://json.schemastore.org/traefik-v2-file-provider.json
# {{ if env "PROXY_UPSTREAMS_HTTPS" }}
http:
  routers:
    https-redirect:
      rule: 'PathPrefix(`/`)'
      entryPoints: ["http"]
      middlewares: ["https-redirect"]
      service: "noop@internal"
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: "https"
        permanent: true
# {{ end }}
# {{ if or ( env "PROXY_UPSTREAMS_HTTPS" ) ( env "PROXY_UPSTREAMS_SMTPS" ) ( env "PROXY_UPSTREAMS_SMTP_STARTTLS" ) }}
tcp:
  routers:
    # {{ range $i, $v := regexSplit "[,\n]+" ( env "PROXY_UPSTREAMS_HTTPS" ) -1 | compact }}
    proxy-https-{{ $v }}:
      rule: 'HostSNI(`{{ $v }}`)'
      entryPoints: ["https"]
      service: "proxy-https-{{ $v }}"
      tls: { passthrough: true }
    # {{ end }}
    # {{ range $i, $v := regexSplit "[,\n]+" ( env "PROXY_UPSTREAMS_SMTPS" ) -1 | compact }}
    proxy-smtps-{{ $v }}:
      rule: 'HostSNI(`{{ $v }}`)'
      entryPoints: ["smtps"]
      service: "proxy-smtps-{{ $v }}"
      tls: { passthrough: true }
    # {{ end }}
    # {{ range $i, $v := regexSplit "[,\n]+" ( env "PROXY_UPSTREAMS_SMTP_STARTTLS" ) -1 | compact }}
    # NOTICE: this only supports a single host, as Traefik does not yet support SMTP with StartTLS.
    proxy-smtp-starttls-{{ $v }}:
      rule: 'HostSNI(`*`)'
      entryPoints: ["smtp-starttls"]
      service: "proxy-smtp-starttls-{{ $v }}"
      # tls: { passthrough: true }
    # {{ end }}
  services:
    # {{ range $i, $v := regexSplit "[,\n]+" ( env "PROXY_UPSTREAMS_HTTPS" ) -1 | compact }}
    proxy-https-{{ $v }}:
      loadBalancer:
        servers: [{ address: "{{ $v }}:443" }]
    # {{ end }}
    # {{ range $i, $v := regexSplit "[,\n]+" ( env "PROXY_UPSTREAMS_SMTPS" ) -1 | compact }}
    proxy-smtps-{{ $v }}:
      loadBalancer:
        servers: [{ address: "{{ $v }}:465" }]
    # {{ end }}
    # {{ range $i, $v := regexSplit "[,\n]+" ( env "PROXY_UPSTREAMS_SMTP_STARTTLS" ) -1 | compact }}
    proxy-smtp-starttls-{{ $v }}:
      loadBalancer:
        servers: [{ address: "{{ $v }}:587" }]
    # {{ end }}
# {{ end }}
