name: 'Main'

on:
  push:
    tags: ['*']
    branches: ['*']
  pull_request:
    branches: ['*']
  workflow_dispatch:

permissions: {}

jobs:

  build:
    name: 'Build Docker images'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332'
      - name: 'Set up QEMU'
        uses: 'docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3'
      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4'
      - name: 'Login to Docker Hub'
        if: "github.event_name != 'pull_request'"
        uses: 'docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446'
        with:
          registry: 'docker.io'
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: 'Extract metadata'
        id: 'meta'
        uses: 'docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81'
        with:
          images: |
            docker.io/hectorm/proxy
          tags: |
            type=ref,event=branch
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
      - name: 'Build and push'
        uses: 'docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1'
        with:
          context: './'
          platforms: 'linux/amd64,linux/arm64/v8'
          tags: '${{ steps.meta.outputs.tags }}'
          labels: '${{ steps.meta.outputs.labels }}'
          push: "${{ github.event_name != 'pull_request' }}"

  release:
    name: 'Create GitHub release'
    if: "startsWith(github.ref, 'refs/tags/v')"
    needs: ['build']
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
    steps:
      - name: 'Create release'
        uses: 'hectorm/ghaction-release@066200d04c3549852afa243d631ea3dc93390f68'
