# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Main"

on:
  push:
    tags: ["*"]
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: "Build Docker images"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf"
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349"
      - name: "Login to Docker Hub"
        if: "github.event_name != 'pull_request'"
        uses: "docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567"
        with:
          registry: "docker.io"
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: "Extract metadata"
        id: "meta"
        uses: "docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81"
        with:
          images: |
            docker.io/hectorm/proxy
          tags: |
            type=ref,event=branch
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
      - name: "Build and push"
        uses: "docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75"
        with:
          context: "./"
          platforms: "linux/amd64,linux/arm64/v8"
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          push: "${{ github.event_name != 'pull_request' }}"

  release:
    name: "Create GitHub release"
    if: "startsWith(github.ref, 'refs/tags/v')"
    needs: ["build"]
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Create release"
        uses: "hectorm/ghaction-release@066200d04c3549852afa243d631ea3dc93390f68"
