# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Main"

on:
  push:
    tags: ["*"]
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: "Build Docker images"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd"
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a"
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd"
      - name: "Login to Docker Hub"
        if: "github.event_name != 'pull_request'"
        uses: "docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2"
        with:
          registry: "docker.io"
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: "Extract metadata"
        id: "meta"
        uses: "docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf"
        with:
          images: |
            docker.io/hectorm/proxy
          tags: |
            type=ref,event=branch
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
      - name: "Build and push"
        uses: "docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294"
        with:
          context: "./"
          platforms: "linux/amd64,linux/arm64/v8"
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          push: "${{ github.event_name != 'pull_request' }}"

  release:
    name: "Create GitHub release"
    if: "startsWith(github.ref, 'refs/tags/v')"
    needs: ["build"]
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Create release"
        uses: "hectorm/ghaction-release@d0426a7a369ce2c1ed615e1a583788b22745ccfe"
